//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.02 at 09:01:03 AM EDT 
//


package com.logiqx.dat;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "clrmamepro")
public class Clrmamepro {

    @XmlAttribute(name = "header")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String header;
    @XmlAttribute(name = "forcemerging")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String forcemerging;
    @XmlAttribute(name = "forcenodump")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String forcenodump;
    @XmlAttribute(name = "forcepacking")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String forcepacking;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeader(String value) {
        this.header = value;
    }

    /**
     * Gets the value of the forcemerging property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForcemerging() {
        if (forcemerging == null) {
            return "split";
        } else {
            return forcemerging;
        }
    }

    /**
     * Sets the value of the forcemerging property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForcemerging(String value) {
        this.forcemerging = value;
    }

    /**
     * Gets the value of the forcenodump property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForcenodump() {
        if (forcenodump == null) {
            return "obsolete";
        } else {
            return forcenodump;
        }
    }

    /**
     * Sets the value of the forcenodump property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForcenodump(String value) {
        this.forcenodump = value;
    }

    /**
     * Gets the value of the forcepacking property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForcepacking() {
        if (forcepacking == null) {
            return "zip";
        } else {
            return forcepacking;
        }
    }

    /**
     * Sets the value of the forcepacking property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForcepacking(String value) {
        this.forcepacking = value;
    }

}
